apiVersion: v1
kind: Service
metadata:
  name: mongoexp-service
spec:
  selector:
    app: mongoexp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexp
  labels:
    app: mongoexp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoexp
  template:
    metadata:
      labels:
        app: mongoexp
    spec:
      containers:
      - name: mongoexpress
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_BASICAUTH_USERNAME
          valueFrom:
           secretKeyRef:
            name: mongosecret
            key: username
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          valueFrom:
           secretKeyRef:
            name: mongosecret
            key: password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
           configMapKeyRef:
            name: mongodep-configmap
            key: databse_url

