apiVersion: v1
kind: Service
metadata:
  name: mongodep-service
spec:
  selector:
    app: mongodep
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodep
  labels:
    app: mongodep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodep
  template:
    metadata:
      labels:
        app: mongodep
    spec:
      containers:
      - name: mongodep
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
           secretKeyRef:
            name: mongosecret
            key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
           secretKeyRef:
            name: mongosecret
            key: password

